<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.1.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Onlinefragebogen Formular Übermittlung',
	'heading' => 'Neue Formularübermittlung',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Aktiviert',
		'checkbox_unchecked' => 'Nicht aktiviert',
		'submitted_from' => 'Von Website übermitteltes Formular: %s',
		'submitted_by' => 'Besucher-IP-Adresse: %s',
		'too_many_submissions' => 'Zu viele Sendungen in letzter Zeit von dieser IP',
		'failed_to_send_email' => 'E-Mail konnte nicht gesendet werden',
		'invalid_reCAPTCHA_private_key' => 'Ungültiger privater reCAPTCHA-Schlüssel.',
		'invalid_reCAPTCHA2_private_key' => 'Ungültiger privater reCAPTCHA 2.0-Schlüssel.',
		'invalid_reCAPTCHA2_server_response' => 'Ungültige private reCAPTCHA 2.0-Server-Reaktionszeit.',
		'invalid_field_type' => 'Unbekannter Feldtyp „%s“.',
		'invalid_form_config' => 'Die Konfiguration im Feld „%s“ ist ungültig.',
		'unknown_method' => 'Unbekannte Serveranfragemethode'
	),
	'email' => array(
		'from' => 'info@lichtblickpflege.de',
		'to' => 'info@lichtblickpflege.de'
	),
	'fields' => array(
		'custom_U6588' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Adresse der Pflegebedürftigen',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Adresse der Pflegebedürftigen“ ist erforderlich.'
			)
		),
		'custom_U6600' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Beginn der Pflege',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Beginn der Pflege“ ist erforderlich.'
			)
		),
		'custom_U6612' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Name des Pflegebedürftigen',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Name des Pflegebedürftigen“ ist erforderlich.'
			)
		),
		'custom_U6698' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Gewicht',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Gewicht“ ist erforderlich.'
			)
		),
		'custom_U6710' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Größe',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Größe“ ist erforderlich.'
			)
		),
		'custom_U6722' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Alter',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Alter“ ist erforderlich.'
			)
		),
		'custom_U6734' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Geburtsdatum',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Geburtsdatum“ ist erforderlich.'
			)
		),
		'custom_U6746' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Pflegegrad',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Pflegegrad“ ist erforderlich.'
			)
		),
		'custom_U6797' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Mobilität',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U8603' => array(
			'order' => 58,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Name“ ist erforderlich.'
			)
		),
		'custom_U8615' => array(
			'order' => 59,
			'type' => 'string',
			'label' => 'Straße, Hausnummer',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Straße, Hausnummer“ ist erforderlich.'
			)
		),
		'custom_U8627' => array(
			'order' => 60,
			'type' => 'string',
			'label' => 'PLZ, Ort',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „PLZ, Ort“ ist erforderlich.'
			)
		),
		'custom_U8639' => array(
			'order' => 61,
			'type' => 'string',
			'label' => 'EMail',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „EMail“ ist erforderlich.'
			)
		),
		'custom_U8651' => array(
			'order' => 62,
			'type' => 'string',
			'label' => 'Telefonnummer',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Telefonnummer“ ist erforderlich.'
			)
		),
		'custom_U9080' => array(
			'order' => 73,
			'type' => 'string',
			'label' => 'Wie haben sie von uns erfahren',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U7277' => array(
			'order' => 24,
			'type' => 'radiogroup',
			'label' => 'Schlaganfall',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Schlaganfall“ ist ungültig.'
			)
		),
		'custom_U7394' => array(
			'order' => 27,
			'type' => 'radiogroup',
			'label' => 'Arztbesuche',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Arztbesuche“ ist ungültig.'
			)
		),
		'custom_U7784' => array(
			'order' => 37,
			'type' => 'radiogroup',
			'label' => 'Weitere',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Weitere“ ist ungültig.'
			)
		),
		'custom_U8780' => array(
			'order' => 66,
			'type' => 'radiogroup',
			'label' => 'Betreuungserfahrung',
			'required' => false,
			'optionItems' => array(
				'erforderlich',
				'nicht erforderlich'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Betreuungserfahrung“ ist ungültig.'
			)
		),
		'custom_U6887' => array(
			'order' => 14,
			'type' => 'radiogroup',
			'label' => 'Demenz',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Demenz“ ist ungültig.'
			)
		),
		'custom_U6758' => array(
			'order' => 10,
			'type' => 'radiogroup',
			'label' => 'Pflegedienst ist beauftragt',
			'required' => true,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'required' => 'Feld „Pflegedienst ist beauftragt“ ist erforderlich.',
				'format' => 'Der Wert im Feld „Pflegedienst ist beauftragt“ ist ungültig.'
			)
		),
		'custom_U7043' => array(
			'order' => 18,
			'type' => 'radiogroup',
			'label' => 'Inkontinenz',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Inkontinenz“ ist ungültig.'
			)
		),
		'custom_U8174' => array(
			'order' => 47,
			'type' => 'radiogroup',
			'label' => 'Bügeln',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Bügeln“ ist ungültig.'
			)
		),
		'custom_U7121' => array(
			'order' => 20,
			'type' => 'radiogroup',
			'label' => 'MS-Patient',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „MS-Patient“ ist ungültig.'
			)
		),
		'custom_U8252' => array(
			'order' => 49,
			'type' => 'radiogroup',
			'label' => 'Fenster putzen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Fenster putzen“ ist ungültig.'
			)
		),
		'custom_U8564' => array(
			'order' => 57,
			'type' => 'radiogroup',
			'label' => 'Anrede',
			'required' => true,
			'optionItems' => array(
				'Herr',
				'Frau'
			),
			'errors' => array(
				'required' => 'Feld „Anrede“ ist erforderlich.',
				'format' => 'Der Wert im Feld „Anrede“ ist ungültig.'
			)
		),
		'custom_U7355' => array(
			'order' => 26,
			'type' => 'radiogroup',
			'label' => 'An- und Auskleiden',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „An- und Auskleiden“ ist ungültig.'
			)
		),
		'custom_U8447' => array(
			'order' => 54,
			'type' => 'radiogroup',
			'label' => 'Wäsche waschen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Wäsche waschen“ ist ungültig.'
			)
		),
		'custom_U7511' => array(
			'order' => 30,
			'type' => 'radiogroup',
			'label' => 'Duschen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Duschen“ ist ungültig.'
			)
		),
		'custom_U8213' => array(
			'order' => 48,
			'type' => 'radiogroup',
			'label' => 'Einkaufen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Einkaufen“ ist ungültig.'
			)
		),
		'custom_U7199' => array(
			'order' => 22,
			'type' => 'radiogroup',
			'label' => 'Parkinson',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Parkinson“ ist ungültig.'
			)
		),
		'custom_U6965' => array(
			'order' => 16,
			'type' => 'radiogroup',
			'label' => 'Geistig behindert',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Geistig behindert“ ist ungültig.'
			)
		),
		'custom_U7550' => array(
			'order' => 31,
			'type' => 'radiogroup',
			'label' => 'Freizeitgestaltung',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Freizeitgestaltung“ ist ungültig.'
			)
		),
		'custom_U8291' => array(
			'order' => 50,
			'type' => 'radiogroup',
			'label' => 'Kochen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Kochen“ ist ungültig.'
			)
		),
		'custom_U7862' => array(
			'order' => 39,
			'type' => 'radiogroup',
			'label' => 'Weitere Personen im Haushalt',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Weitere Personen im Haushalt“ ist ungültig.'
			)
		),
		'custom_U8663' => array(
			'order' => 63,
			'type' => 'radiogroup',
			'label' => 'Geschlecht der Pflegekraft',
			'required' => false,
			'optionItems' => array(
				'männlich',
				'weiblich'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Geschlecht der Pflegekraft“ ist ungültig.'
			)
		),
		'custom_U7160' => array(
			'order' => 21,
			'type' => 'radiogroup',
			'label' => 'Osteoporose',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Osteoporose“ ist ungültig.'
			)
		),
		'custom_U8135' => array(
			'order' => 46,
			'type' => 'radiogroup',
			'label' => 'Blumen gießen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Blumen gießen“ ist ungültig.'
			)
		),
		'custom_U8858' => array(
			'order' => 68,
			'type' => 'radiogroup',
			'label' => 'Raucher',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Raucher“ ist ungültig.'
			)
		),
		'custom_U8408' => array(
			'order' => 53,
			'type' => 'radiogroup',
			'label' => 'Speisenplanung',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Speisenplanung“ ist ungültig.'
			)
		),
		'custom_U8486' => array(
			'order' => 55,
			'type' => 'radiogroup',
			'label' => 'Versorgung der Haustiere',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Versorgung der Haustiere“ ist ungültig.'
			)
		),
		'custom_U7589' => array(
			'order' => 32,
			'type' => 'radiogroup',
			'label' => 'Körperpflege',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Körperpflege“ ist ungültig.'
			)
		),
		'custom_U7706' => array(
			'order' => 35,
			'type' => 'radiogroup',
			'label' => 'Toilettengang',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Toilettengang“ ist ungültig.'
			)
		),
		'custom_U8018' => array(
			'order' => 43,
			'type' => 'radiogroup',
			'label' => 'Wohnverhältnisse',
			'required' => false,
			'optionItems' => array(
				'städtisch',
				'ländlich'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Wohnverhältnisse“ ist ungültig.'
			)
		),
		'custom_U7238' => array(
			'order' => 23,
			'type' => 'radiogroup',
			'label' => 'Rheuma',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Rheuma“ ist ungültig.'
			)
		),
		'custom_U6926' => array(
			'order' => 15,
			'type' => 'radiogroup',
			'label' => 'Dialysepatient',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Dialysepatient“ ist ungültig.'
			)
		),
		'custom_U8525' => array(
			'order' => 56,
			'type' => 'radiogroup',
			'label' => 'Weitere',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Weitere“ ist ungültig.'
			)
		),
		'custom_U8897' => array(
			'order' => 69,
			'type' => 'radiogroup',
			'label' => 'Unterbringung',
			'required' => false,
			'optionItems' => array(
				'eigener Bereich',
				'Zimmer'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Unterbringung“ ist ungültig.'
			)
		),
		'custom_U6848' => array(
			'order' => 13,
			'type' => 'radiogroup',
			'label' => 'Arthrose',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Arthrose“ ist ungültig.'
			)
		),
		'custom_U8741' => array(
			'order' => 65,
			'type' => 'radiogroup',
			'label' => 'Gewünschtes Alter der Pflegekraft',
			'required' => false,
			'optionItems' => array(
				'30-40',
				'40-50',
				'50-60'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Gewünschtes Alter der Pflegekraft“ ist ungültig.'
			)
		),
		'custom_U9014' => array(
			'order' => 72,
			'type' => 'radiogroup',
			'label' => 'Internet vorhanden',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Internet vorhanden“ ist ungültig.'
			)
		),
		'custom_U7316' => array(
			'order' => 25,
			'type' => 'radiogroup',
			'label' => 'Andere',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Andere“ ist ungültig.'
			)
		),
		'custom_U8936' => array(
			'order' => 70,
			'type' => 'radiogroup',
			'label' => 'Eigenes Bad',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Eigenes Bad“ ist ungültig.'
			)
		),
		'custom_U7901' => array(
			'order' => 40,
			'type' => 'radiogroup',
			'label' => 'Hund',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Hund“ ist ungültig.'
			)
		),
		'custom_U7082' => array(
			'order' => 19,
			'type' => 'radiogroup',
			'label' => 'Krebs',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Krebs“ ist ungültig.'
			)
		),
		'custom_U7979' => array(
			'order' => 42,
			'type' => 'radiogroup',
			'label' => 'Andere',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Andere“ ist ungültig.'
			)
		),
		'custom_U7667' => array(
			'order' => 34,
			'type' => 'radiogroup',
			'label' => 'Nahrungsaufnahme',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Nahrungsaufnahme“ ist ungültig.'
			)
		),
		'custom_U8819' => array(
			'order' => 67,
			'type' => 'radiogroup',
			'label' => 'Führerschein notwendig',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Führerschein notwendig“ ist ungültig.'
			)
		),
		'custom_U7004' => array(
			'order' => 17,
			'type' => 'radiogroup',
			'label' => 'Herz-Kreislauf',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Herz-Kreislauf“ ist ungültig.'
			)
		),
		'custom_U8975' => array(
			'order' => 71,
			'type' => 'radiogroup',
			'label' => 'eigener Fernseher',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „eigener Fernseher“ ist ungültig.'
			)
		),
		'custom_U8057' => array(
			'order' => 44,
			'type' => 'radiogroup',
			'label' => 'Geschäfte des täglichen Lebens fußläufig erreichbar',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Geschäfte des täglichen Lebens fußläufig erreichbar“ ist ungültig.'
			)
		),
		'custom_U7745' => array(
			'order' => 36,
			'type' => 'radiogroup',
			'label' => 'Stehen, Gehen oder Betten',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Stehen, Gehen oder Betten“ ist ungültig.'
			)
		),
		'custom_U7823' => array(
			'order' => 38,
			'type' => 'radiogroup',
			'label' => 'Sind nächtliche Einsätze notwendig',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Sind nächtliche Einsätze notwendig“ ist ungültig.'
			)
		),
		'custom_U7472' => array(
			'order' => 29,
			'type' => 'radiogroup',
			'label' => 'Behördengänge',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Behördengänge“ ist ungültig.'
			)
		),
		'custom_U7628' => array(
			'order' => 33,
			'type' => 'radiogroup',
			'label' => 'Mobilisierung',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Mobilisierung“ ist ungültig.'
			)
		),
		'custom_U8369' => array(
			'order' => 52,
			'type' => 'radiogroup',
			'label' => 'Sauber machen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Sauber machen“ ist ungültig.'
			)
		),
		'custom_U8096' => array(
			'order' => 45,
			'type' => 'radiogroup',
			'label' => 'Aufräumen',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Aufräumen“ ist ungültig.'
			)
		),
		'custom_U8330' => array(
			'order' => 51,
			'type' => 'radiogroup',
			'label' => 'leichte Gartenarbeit',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „leichte Gartenarbeit“ ist ungültig.'
			)
		),
		'custom_U7433' => array(
			'order' => 28,
			'type' => 'radiogroup',
			'label' => 'Ausflüge',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Ausflüge“ ist ungültig.'
			)
		),
		'custom_U6809' => array(
			'order' => 12,
			'type' => 'radiogroup',
			'label' => 'Alzheimer',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Alzheimer“ ist ungültig.'
			)
		),
		'custom_U6624' => array(
			'order' => 4,
			'type' => 'radiogroup',
			'label' => 'Geschlecht',
			'required' => true,
			'optionItems' => array(
				'männlich',
				'weiblich'
			),
			'errors' => array(
				'required' => 'Feld „Geschlecht“ ist erforderlich.',
				'format' => 'Der Wert im Feld „Geschlecht“ ist ungültig.'
			)
		),
		'custom_U7940' => array(
			'order' => 41,
			'type' => 'radiogroup',
			'label' => 'Katze',
			'required' => false,
			'optionItems' => array(
				'ja',
				'nein'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Katze“ ist ungültig.'
			)
		),
		'custom_U8702' => array(
			'order' => 64,
			'type' => 'radiogroup',
			'label' => 'Gewünschte Deutschkenntnisse',
			'required' => false,
			'optionItems' => array(
				'Grundkenntnisse',
				'mittlere Kenntnisse',
				'gute Kenntnisse',
				'sehr gute Kenntnisse'
			),
			'errors' => array(
				'format' => 'Der Wert im Feld „Gewünschte Deutschkenntnisse“ ist ungültig.'
			)
		)
	)
);

process_form($form);
?>
