<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Anfrage Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'tomasz.szewczyk@hotmail.de',
		'to' => 'tomasz.szewczyk@hotmail.de'
	),
	'fields' => array(
		'custom_U1879' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nachname, Vorname',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Nachname, Vorname\' is required.'
			)
		),
		'Email' => array(
			'order' => 5,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U1873' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Ihre Nachricht',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U1917' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Telefon',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Telefon\' is required.'
			)
		),
		'custom_U1929' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Telefon (geschäftlich)',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U1941' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Firma',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U2209' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Custom',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U2010' => array(
			'order' => 2,
			'type' => 'checkboxgroup',
			'label' => 'Wobei können wir Ihnen helfen?',
			'required' => true,
			'optionItems' => array(
				'Wohnungsauflösung',
				'Entrümpelung',
				'Entsorgung von Elektroschrott',
				'Wohnungsrenovierung',
				'Umzug',
				'Transport',
				'Sonstiges (bitte im Feld unten eingeben)'
			),
			'errors' => array(
				'required' => 'Field \'Wobei können wir Ihnen helfen?\' is required.',
				'format' => 'Field \'Wobei können wir Ihnen helfen?\' has an invalid value.'
			)
		),
		'custom_U2135' => array(
			'order' => 9,
			'type' => 'radiogroup',
			'label' => 'Wie sollen wir Sie kontaktieren?',
			'required' => true,
			'optionItems' => array(
				'telefonisch',
				'E-Mail'
			),
			'errors' => array(
				'required' => 'Field \'Wie sollen wir Sie kontaktieren?\' is required.',
				'format' => 'Field \'Wie sollen wir Sie kontaktieren?\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
