<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.1.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Kontakt Übermittlung',
	'heading' => 'Neue Formularübermittlung',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Aktiviert',
		'checkbox_unchecked' => 'Nicht aktiviert',
		'submitted_from' => 'Von Website übermitteltes Formular: %s',
		'submitted_by' => 'Besucher-IP-Adresse: %s',
		'too_many_submissions' => 'Zu viele Sendungen in letzter Zeit von dieser IP',
		'failed_to_send_email' => 'E-Mail konnte nicht gesendet werden',
		'invalid_reCAPTCHA_private_key' => 'Ungültiger privater reCAPTCHA-Schlüssel.',
		'invalid_reCAPTCHA2_private_key' => 'Ungültiger privater reCAPTCHA 2.0-Schlüssel.',
		'invalid_reCAPTCHA2_server_response' => 'Ungültige private reCAPTCHA 2.0-Server-Reaktionszeit.',
		'invalid_field_type' => 'Unbekannter Feldtyp „%s“.',
		'invalid_form_config' => 'Die Konfiguration im Feld „%s“ ist ungültig.',
		'unknown_method' => 'Unbekannte Serveranfragemethode'
	),
	'email' => array(
		'from' => 'info@lichtblickpflege.de',
		'to' => 'info@lichtblickpflege.de'
	),
	'fields' => array(
		'custom_U1272' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Ihr Name',
			'required' => false,
			'errors' => array(
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Ihre EMail Adresse',
			'required' => false,
			'errors' => array(
				'format' => 'Die E-Mail-Adresse in Feld „Ihre EMail Adresse“ ist ungültig.'
			)
		),
		'custom_U1268' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Ihre Nachricht',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U6195' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Ihre Telefonnummer',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
